[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 4_294_967_295
etherscan_api_key = '${ETHERSCAN_API_KEY}'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config